name: we_chat
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^3.0.1
  firebase_core: ^2.24.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter

#   flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#   android: "ics_launcher"
#   ios: true
#   image_path: "images/chat.png"
#   min_sdk_android: 21
#   remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
