name: we_chat
description: "A new Flutter project."

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_lints: ^3.0.1

  # for using cupertion icons
  cupertino_icons: ^1.0.2

  # for integrate firebase 
  firebase_core: ^2.24.2

  # for handling google sign in
  google_sign_in: ^6.2.1

  # for handling firebase authentication
  firebase_auth: ^4.15.3

  # for accessing cloud firestore data base 
  cloud_firestore: ^4.14.0

  # for showing network image
  cached_network_image: ^3.3.1

  # for picking images
  image_picker: ^1.0.7

  # for accessing firebase storage (for uploading files)
  firebase_storage: ^11.6.0


dev_dependencies:
  flutter_test:
    sdk: flutter

#   flutter_launcher_icons: "^0.13.1"

# flutter_launcher_icons:
#   android: "ics_launcher"
#   ios: true
#   image_path: "images/chat.png"
#   min_sdk_android: 21
#   remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
